export enum QueryKey {
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_CATEGORIES_SETTINGS = 'GET_CATEGORIES_SETTINGS',
  GET_STORIES = 'GET_STORIES',
  GET_STORY = 'GET_STORY',
  GET_INGREDIENTS = 'GET_INGREDIENTS',
  GET_INGREDIENT = 'GET_INGREDIENT',
  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_ORDERS = 'GET_ORDERS',
}
