export const STORY_ITEM_WIDTH = 520
export const STORY_ITEM_HEIGHT = 684
export const STORY_PREVIEW_WIDTH = 200
export const STORY_PREVIEW_HEIGHT = 250
export const STORY_ITEM_ASPECT = STORY_ITEM_WIDTH / STORY_ITEM_HEIGHT
export const STORY_PREVIEW_ASPECT = STORY_PREVIEW_WIDTH / STORY_PREVIEW_HEIGHT
